[tools]
golang = "latest"
bun = "latest"
npm = "latest"
prettier = "latest"
pre-commit = "latest"
python = "latest"
uv = "latest"

[settings]

[settings.npm]
package_manager = "bun"

[settings.pipx]
uvx = true
